services:
  db-nutrition-dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Europe/Paris
      LANG: en_US.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql # Initialise le containeur avec le dump
      - ./docker/db/volume:/var/lib/mysql # Résilience des modifications
