services:
  webapp:
    image: nutrition_webapp
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
    depends_on:
      - db-nutrition

  db-nutrition:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Paris
      LANG: en_US.UTF-8
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/:/docker-entrypoint-initdb.d/
      - ./docker/db/volume:/var/lib/mysql
