services:
  db-nutrition:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nutrition_webapp
      TZ: Europe/Paris
      LANG: en_US.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql # Initialise le containeur avec le dump
      - ./docker/db/volume:/var/lib/mysql # Résilience des modifications
